const extensionId = "com.kagi.Kagi-Search-for-Safari.Extension (TFVG979488)";
document.getElementById("open-app").onclick = function() {
    browser.runtime.sendNativeMessage(extensionId, {"type": "openApp"}, function(response) {
        window.close();
    });
}



const googleUrls = {
    "google.com.au": "q",
    "google.md": "q",
    "google.ru": "q",
    "google.me": "q",
    "google.com.qa": "q",
    "google.com.gt": "q",
    "google.se": "q",
    "google.tm": "q",
    "google.vg": "q",
    "google.it": "q",
    "google.cat": "q",
    "google.com.ru": "q",
    "google.com.gr": "q",
    "google.ee": "q",
    "google.cd": "q",
    "google.sk": "q",
    "google.com.ly": "q",
    "google.hn": "q",
    "google.co.jp": "q",
    "google.ad": "q",
    "google.com.sg": "q",
    "google.ie": "q",
    "google.co.vi": "q",
    "google.kg": "q",
    "google.com.kh": "q",
    "google.co.ck": "q",
    "google.is": "q",
    "google.tt": "q",
    "google.vu": "q",
    "google.bg": "q",
    "google.ch": "q",
    "google.com.sa": "q",
    "google.tn": "q",
    "google.pl": "q",
    "google.ro": "q",
    "google.gm": "q",
    "google.tl": "q",
    "google.mg": "q",
    "google.dk": "q",
    "google.com.bo": "q",
    "google.je": "q",
    "google.com.kw": "q",
    "google.dz": "q",
    "google.ga": "q",
    "google.com.gh": "q",
    "google.lt": "q",
    "google.com.ag": "q",
    "google.ps": "q",
    "google.com.vc": "q",
    "google.com.pr": "q",
    "google.co.cr": "q",
    "google.pn": "q",
    "google.com.tr": "q",
    "google.sn": "q",
    "google.tg": "q",
    "google.gg": "q",
    "google.gr": "q",
    "google.com.mt": "q",
    "google.nu": "q",
    "google.cm": "q",
    "google.lk": "q",
    "google.co.mz": "q",
    "google.cv": "q",
    "google.sm": "q",
    "google.no": "q",
    "google.al": "q",
    "google.bi": "q",
    "google.com.af": "q",
    "google.sr": "q",
    "google.jo": "q",
    "google.sh": "q",
    "google.co.uk": "q",
    "google.co.bw": "q",
    "google.dm": "q",
    "google.at": "q",
    "google.co.ug": "q",
    "google.dj": "q",
    "google.si": "q",
    "google.com.pg": "q",
    "google.com.tj": "q",
    "google.co.za": "q",
    "google.nl": "q",
    "google.sc": "q",
    "google.ae": "q",
    "google.mv": "q",
    "google.ne": "q",
    "google.gy": "q",
    "google.com.sl": "q",
    "google.co.in": "q",
    "google.com.bn": "q",
    "google.ht": "q",
    "google.com.ua": "q",
    "google.com.my": "q",
    "google.co.kr": "q",
    "google.com": "q",
    "google.by": "q",
    "google.com.cu": "q",
    "google.com.lb": "q",
    "google.co.nz": "q",
    "google.mu": "q",
    "google.com.om": "q",
    "google.as": "q",
    "google.com.pe": "q",
    "google.mk": "q",
    "google.td": "q",
    "google.es": "q",
    "google.az": "q",
    "google.com.hk": "q",
    "google.com.do": "q",
    "google.bt": "q",
    "google.am": "q",
    "google.fm": "q",
    "google.com.mx": "q",
    "google.fi": "q",
    "google.com.bz": "q",
    "google.st": "q",
    "google.com.vn": "q",
    "google.rs": "q",
    "google.bs": "q",
    "google.cn": "q",
    "google.com.pa": "q",
    "google.com.sb": "q",
    "google.lv": "q",
    "google.co.uz": "q",
    "google.co.hu": "q",
    "google.co.ve": "q",
    "google.co.zw": "q",
    "google.com.ai": "q",
    "google.com.co": "q",
    "google.ci": "q",
    "google.com.uy": "q",
    "google.cl": "q",
    "google.mw": "q",
    "google.cz": "q",
    "google.co.il": "q",
    "google.co.th": "q",
    "google.be": "q",
    "google.hr": "q",
    "google.fr": "q",
    "google.im": "q",
    "google.com.ec": "q",
    "google.cg": "q",
    "google.iq": "q",
    "google.com.np": "q",
    "google.gl": "q",
    "google.co.ke": "q",
    "google.co.id": "q",
    "google.ml": "q",
    "google.ms": "q",
    "google.com.ni": "q",
    "google.mn": "q",
    "google.ki": "q",
    "google.lu": "q",
    "google.hu": "q",
    "google.rw": "q",
    "google.co.ma": "q",
    "google.com.tw": "q",
    "google.co.ls": "q",
    "google.com.et": "q",
    "google.li": "q",
    "google.com.br": "q",
    "google.bj": "q",
    "google.com.py": "q",
    "google.co.tz": "q",
    "google.ba": "q",
    "google.co.ao": "q",
    "google.bf": "q",
    "google.com.ph": "q",
    "google.com.sv": "q",
    "google.com.bd": "q",
    "google.com.mm": "q",
    "google.la": "q",
    "google.ws": "q",
    "google.com.fj": "q",
    "google.co.zm": "q",
    "google.cf": "q",
    "google.nr": "q",
    "google.to": "q",
    "google.com.jm": "q",
    "google.com.ar": "q",
    "google.com.gi": "q",
    "google.ca": "q",
    "google.kz": "q",
    "google.com.cy": "q",
    "google.de": "q",
    "google.com.na": "q",
    "google.com.pk": "q",
    "google.pt": "q",
    "google.ge": "q",
    "google.so": "q",
    "google.com.bh": "q",
    "google.com.eg": "q",
    "google.com.ng": "q"
};

document.getElementById("request-permissions").onclick = function() {
    var permissionsToRequest = {
        permissions: ["webNavigation"],
        origins: Object.keys(googleUrls).map((host) => ("*://" + host + "/*"))
    }
    browser.permissions.request(permissionsToRequest);
}

function updatePermissions() {
  browser.permissions.getAll()
  .then((permissions) => {
    document.getElementById('permissions').innerText = permissions.permissions.join(', ');
  });
}

updatePermissions();
